export const theme = {
  defaultTheme: 'dark',
  themes: {
    // OLED mobile - pure black
    dark: {
      dark: true,
      colors: {
        background: '#000000',
        surface: '#0A0A0A',
        'surface-bright': '#141414',
        'surface-light': '#0F0F0F',
        'surface-variant': '#1C1C1C',
        'on-surface-variant': '#E0E0E0',
        primary: '#FFFFFF',
        'primary-darken-1': '#CCCCCC',
        secondary: '#B0B0B0',
        'secondary-darken-1': '#888888',
        error: '#CF6679',
        info: '#89B4E8',
        success: '#81C995',
        warning: '#FFB74D',
        'on-background': '#FFFFFF',
        'on-surface': '#FFFFFF',
        'on-primary': '#000000',
        'on-secondary': '#000000',
        'on-error': '#000000',
        'on-info': '#000000',
        'on-success': '#000000',
        'on-warning': '#000000',
      },
    },
    // LCD web - softer dark gray
    'dark-web': {
      dark: true,
      colors: {
        background: '#0F0F0F',
        surface: '#1A1A1A',
        'surface-bright': '#242424',
        'surface-light': '#1F1F1F',
        'surface-variant': '#2E2E2E',
        'on-surface-variant': '#E0E0E0',
        primary: '#FFFFFF',
        'primary-darken-1': '#CCCCCC',
        secondary: '#B0B0B0',
        'secondary-darken-1': '#888888',
        error: '#CF6679',
        info: '#89B4E8',
        success: '#81C995',
        warning: '#FFB74D',
        'on-background': '#FFFFFF',
        'on-surface': '#FFFFFF',
        'on-primary': '#000000',
        'on-secondary': '#000000',
        'on-error': '#000000',
        'on-info': '#000000',
        'on-success': '#000000',
        'on-warning': '#000000',
      },
    },
  },
}
